// Top-level build file (Groovy DSL)
// 注意: plugins{} 块必须在最前面

plugins {
    id 'com.android.application' version '7.4.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.22' apply false
}

buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/google'}
        maven { url 'https://maven.aliyun.com/public'}
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.22'
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/google'}
        maven { url 'https://maven.aliyun.com/public'}
        google()
        mavenCentral()
    }
}
