pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/google'}
        maven { url 'https://maven.aliyun.com/public'}
        maven { url 'https://maven.aliyun.com/gradle'}
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "IncomeMeter"
include ':app'
